-- DROP DATABASE
DROP DATABASE IF EXISTS ecommerce_db;

-- CREATE DATABASE
CREATE DATABASE ecommerce_db;

CREATE TABLE category (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  category_name STRING NOT NULL
);

CREATE TABLE product (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  product_name STRING NOT NULL,
  price DECIMAL BOOLEAN NOT NULL,
  stock INT BOOLEAN NOT NULL,
  category_id INT,
  REFERENCES category(id)
);

CREATE TABLE tag (
   id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  tag_name STRING
);

CREATE TABLE productTag (
   id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  product_id INT REFERENCES product(id),
  tag_id INT,
  REFERENCES tag(id) 
);